Model: gpt-4
Provider: AItianhuSpace
Error: <urlopen error [Errno 11001] getaddrinfo failed>
Time taken: 24.20 seconds

Model: gpt-4
Provider: Aichatos
Error: Cannot connect to host api.binjie.fun:443 ssl:default [getaddrinfo failed]
Time taken: 8.09 seconds

Model: gpt-4
Provider: Aura
Error: <urlopen error [Errno 11001] getaddrinfo failed>
Time taken: 0.10 seconds

Model: gpt-4
Provider: Bing
Error: Cannot connect to host www.bing.com:443 ssl:default [getaddrinfo failed]
Time taken: 0.01 seconds

Model: gpt-4
Provider: BingCreateImages
Error: Cannot connect to host www.bing.com:443 ssl:default [getaddrinfo failed]
Time taken: 0.27 seconds

Model: gpt-4
Provider: Blackbox
Error: Cannot connect to host www.blackbox.ai:443 ssl:default [getaddrinfo failed]
Time taken: 0.01 seconds

Model: gpt-4
Provider: ChatForAi
Error: Failed to perform, curl: (6) Could not resolve host: chatforai.store. See https://curl.se/libcurl/c/libcurl-errors.html first for more details.
Time taken: 0.20 seconds

Model: gpt-4
Provider: Chatgpt4Online
Error: <urlopen error [Errno 11001] getaddrinfo failed>
Time taken: 0.19 seconds

Model: gpt-4
Provider: ChatgptAi
Error: Cannot connect to host chatgpt.ai:443 ssl:default [getaddrinfo failed]
Time taken: 0.01 seconds

Model: gpt-4
Provider: ChatgptNext
Error: Cannot connect to host chat.fstha.com:443 ssl:default [getaddrinfo failed]
Time taken: 0.01 seconds

Model: gpt-4
Provider: ChatgptX
Error: Cannot connect to host chatgptx.de:443 ssl:default [getaddrinfo failed]
Time taken: 0.01 seconds

Model: gpt-4
Provider: Cnote
Error: Cannot connect to host p1api.xjai.pro:443 ssl:default [getaddrinfo failed]
Time taken: 0.00 seconds

Model: gpt-4
Provider: DeepInfra
Error: Add a "api_key"
Time taken: 0.00 seconds

Model: gpt-4
Provider: DeepInfraImage
Error: HTTPSConnectionPool(host='api.deepinfra.com', port=443): Max retries exceeded with url: /models/featured (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001F094208D60>: Failed to resolve 'api.deepinfra.com' ([Errno 11001] getaddrinfo failed)"))
Time taken: 0.01 seconds

Model: gpt-4
Provider: Feedough
Error: Cannot connect to host www.feedough.com:443 ssl:default [getaddrinfo failed]
Time taken: 0.00 seconds

Model: gpt-4
Provider: FlowGpt
Error: Model is not supported: gpt-4 in: FlowGpt
Time taken: 0.00 seconds

Model: gpt-4
Provider: FreeChatgpt
Error: Cannot connect to host free.chatgpt.org.uk:443 ssl:default [getaddrinfo failed]
Time taken: 0.00 seconds

Model: gpt-4
Provider: FreeGpt
Error: Failed to perform, curl: (6) Could not resolve host: s.aifree.site. See https://curl.se/libcurl/c/libcurl-errors.html first for more details.
Time taken: 0.01 seconds

Model: gpt-4
Provider: Gemini
Error: Cannot connect to host gemini.google.com:443 ssl:default [getaddrinfo failed]
Time taken: 0.09 seconds

Model: gpt-4
Provider: GeminiPro
Error: Model is not supported: gpt-4 in: GeminiPro
Time taken: 0.00 seconds

Model: gpt-4
Provider: GeminiProChat
Error: Cannot connect to host www.chatgemini.net:443 ssl:default [getaddrinfo failed]
Time taken: 0.01 seconds

Model: gpt-4
Provider: GigaChat
Error: Model is not supported: gpt-4 in: GigaChat
Time taken: 0.00 seconds

Model: gpt-4
Provider: GptTalkRu
Error: Install "selenium-wire" package
Time taken: 0.00 seconds

Model: gpt-4
Provider: Groq
Error: Add a "api_key"
Time taken: 0.00 seconds

Model: gpt-4
Provider: HuggingChat
Response: 
Time taken: 0.00 seconds

Model: gpt-4
Provider: HuggingFace
Error: Cannot connect to host api-inference.huggingface.co:443 ssl:default [getaddrinfo failed]
Time taken: 0.01 seconds

Model: gpt-4
Provider: Koala
Error: Cannot connect to host koala.sh:443 ssl:default [getaddrinfo failed]
Time taken: 0.04 seconds

Model: gpt-4
Provider: Liaobots
Error: Cannot connect to host liaobots.work:443 ssl:False [getaddrinfo failed]
Time taken: 0.03 seconds

Model: gpt-4
Provider: Local
Error: Install "gpt4all" package | pip install -U g4f[local]
Time taken: 0.00 seconds

Model: gpt-4
Provider: MetaAI
Error: Cannot connect to host www.meta.ai:443 ssl:default [getaddrinfo failed]
Time taken: 0.01 seconds

Model: gpt-4
Provider: MetaAIAccount
Error: Cannot connect to host www.meta.ai:443 ssl:default [getaddrinfo failed]
Time taken: 0.11 seconds

Model: gpt-4
Provider: MyShell
Error: <urlopen error [Errno 11001] getaddrinfo failed>
Time taken: 0.09 seconds

Model: gpt-4
Provider: Ollama
Error: HTTPConnectionPool(host='127.0.0.1', port=11434): Max retries exceeded with url: /api/tags (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001F094248640>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
Time taken: 2.03 seconds

Model: gpt-4
Provider: OpenRouter
Error: Add a "api_key"
Time taken: 0.00 seconds

Model: gpt-4
Provider: Openai
Error: Add a "api_key"
Time taken: 0.00 seconds

Model: gpt-4
Provider: OpenaiAccount
Error: No .har file found
Time taken: 0.00 seconds

Model: gpt-4
Provider: OpenaiChat
Error: Cannot connect to host chatgpt.com:443 ssl:default [getaddrinfo failed]
Time taken: 0.00 seconds

Model: gpt-4
Provider: PerplexityAi
Error: <urlopen error [Errno 11001] getaddrinfo failed>
Time taken: 0.08 seconds

Model: gpt-4
Provider: PerplexityApi
Error: Add a "api_key"
Time taken: 0.00 seconds

Model: gpt-4
Provider: PerplexityLabs
Error: Failed to perform, curl: (6) Could not resolve host: www.perplexity.ai. See https://curl.se/libcurl/c/libcurl-errors.html first for more details.
Time taken: 0.01 seconds

Model: gpt-4
Provider: Pi
Error: <urlopen error [Errno 11001] getaddrinfo failed>
Time taken: 0.05 seconds

Model: gpt-4
Provider: Pizzagpt
Error: Cannot connect to host www.pizzagpt.it:443 ssl:default [getaddrinfo failed]
Time taken: 0.00 seconds

Model: gpt-4
Provider: Poe
Error: <urlopen error [Errno 11001] getaddrinfo failed>
Time taken: 0.05 seconds

Model: gpt-4
Provider: Raycast
Error: HTTPSConnectionPool(host='backend.raycast.com', port=443): Max retries exceeded with url: /api/v1/ai/chat_completions (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001F094249570>: Failed to resolve 'backend.raycast.com' ([Errno 11001] getaddrinfo failed)"))
Time taken: 0.00 seconds

Model: gpt-4
Provider: Reka
Error: No cookies found for chat.reka.ai
Time taken: 0.05 seconds

Model: gpt-4
Provider: Replicate
Error: api_key is missing
Time taken: 0.00 seconds

Model: gpt-4
Provider: ReplicateImage
Error: Failed to perform, curl: (6) Could not resolve host: homepage.replicate.com. See https://curl.se/libcurl/c/libcurl-errors.html first for more details.
Time taken: 0.01 seconds

Model: gpt-4
Provider: TalkAi
Error: <urlopen error [Errno 11001] getaddrinfo failed>
Time taken: 0.05 seconds

Model: gpt-4
Provider: Theb
Error: <urlopen error [Errno 11001] getaddrinfo failed>
Time taken: 0.06 seconds

Model: gpt-4
Provider: ThebApi
Error: Add a "api_key"
Time taken: 0.00 seconds

Model: gpt-4
Provider: Vercel
Error: HTTPSConnectionPool(host='chat.vercel.ai', port=443): Max retries exceeded with url: /openai.jpeg (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001F0942482E0>: Failed to resolve 'chat.vercel.ai' ([Errno 11001] getaddrinfo failed)"))
Time taken: 0.00 seconds

Model: gpt-4
Provider: WhiteRabbitNeo
Error: Cannot connect to host www.whiterabbitneo.com:443 ssl:default [getaddrinfo failed]
Time taken: 0.05 seconds

Model: gpt-4
Provider: You
Error: [WinError 1225] The remote computer refused the network connection
Time taken: 14.11 seconds

Model: gpt-4
Provider: Yqcloud
Error: Failed to perform, curl: (6) Could not resolve host: api.aichatos.cloud. See https://curl.se/libcurl/c/libcurl-errors.html first for more details.
Time taken: 12.04 seconds

Model: gpt-4o
Provider: AItianhuSpace
Error: <urlopen error [Errno 11001] getaddrinfo failed>
Time taken: 0.05 seconds

Model: gpt-4o
Provider: Aichatos
Error: Cannot connect to host api.binjie.fun:443 ssl:default [getaddrinfo failed]
Time taken: 0.02 seconds

Model: gpt-4o
Provider: Aura
Error: <urlopen error [Errno 11001] getaddrinfo failed>
Time taken: 0.03 seconds

Model: gpt-4o
Provider: Bing
Error: Cannot connect to host www.bing.com:443 ssl:default [getaddrinfo failed]
Time taken: 0.00 seconds

Model: gpt-4o
Provider: BingCreateImages
Error: Cannot connect to host www.bing.com:443 ssl:default [getaddrinfo failed]
Time taken: 0.05 seconds

Model: gpt-4o
Provider: Blackbox
Error: Cannot connect to host www.blackbox.ai:443 ssl:default [getaddrinfo failed]
Time taken: 0.00 seconds

Model: gpt-4o
Provider: ChatForAi
Error: Failed to perform, curl: (6) Could not resolve host: chatforai.store. See https://curl.se/libcurl/c/libcurl-errors.html first for more details.
Time taken: 0.01 seconds

Model: gpt-4o
Provider: Chatgpt4Online
Error: <urlopen error [Errno 11001] getaddrinfo failed>
Time taken: 0.04 seconds

Model: gpt-4o
Provider: ChatgptAi
Error: Cannot connect to host chatgpt.ai:443 ssl:default [getaddrinfo failed]
Time taken: 0.00 seconds

Model: gpt-4o
Provider: ChatgptNext
Error: Cannot connect to host chat.fstha.com:443 ssl:default [getaddrinfo failed]
Time taken: 0.00 seconds

Model: gpt-4o
Provider: ChatgptX
Error: Cannot connect to host chatgptx.de:443 ssl:default [getaddrinfo failed]
Time taken: 0.00 seconds

Model: gpt-4o
Provider: Cnote
Error: Cannot connect to host p1api.xjai.pro:443 ssl:default [getaddrinfo failed]
Time taken: 0.00 seconds

Model: gpt-4o
Provider: DeepInfra
Error: Add a "api_key"
Time taken: 0.00 seconds

Model: gpt-4o
Provider: DeepInfraImage
Error: HTTPSConnectionPool(host='api.deepinfra.com', port=443): Max retries exceeded with url: /models/featured (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000002BE3EABD7B0>: Failed to resolve 'api.deepinfra.com' ([Errno 11001] getaddrinfo failed)"))
Time taken: 0.00 seconds

Model: gpt-4o
Provider: Feedough
Error: Cannot connect to host www.feedough.com:443 ssl:default [getaddrinfo failed]
Time taken: 0.00 seconds

Model: gpt-4o
Provider: FlowGpt
Error: Model is not supported: gpt-4o in: FlowGpt
Time taken: 0.00 seconds

Model: gpt-4o
Provider: FreeChatgpt
Error: Cannot connect to host free.chatgpt.org.uk:443 ssl:default [getaddrinfo failed]
Time taken: 0.00 seconds

Model: gpt-4o
Provider: FreeGpt
Error: Failed to perform, curl: (6) Could not resolve host: s.aifree.site. See https://curl.se/libcurl/c/libcurl-errors.html first for more details.
Time taken: 0.00 seconds

Model: gpt-4o
Provider: Gemini
Error: Cannot connect to host gemini.google.com:443 ssl:default [getaddrinfo failed]
Time taken: 0.02 seconds

Model: gpt-4o
Provider: GeminiPro
Error: Model is not supported: gpt-4o in: GeminiPro
Time taken: 0.00 seconds

Model: gpt-4o
Provider: GeminiProChat
Error: Cannot connect to host www.chatgemini.net:443 ssl:default [getaddrinfo failed]
Time taken: 0.00 seconds

Model: gpt-4o
Provider: GigaChat
Error: Model is not supported: gpt-4o in: GigaChat
Time taken: 0.00 seconds

Model: gpt-4o
Provider: GptTalkRu
Error: Install "selenium-wire" package
Time taken: 0.00 seconds

Model: gpt-4o
Provider: Groq
Error: Add a "api_key"
Time taken: 0.00 seconds

Model: gpt-4o
Provider: HuggingChat
Response: 
Time taken: 0.00 seconds

Model: gpt-4o
Provider: HuggingFace
Error: Cannot connect to host api-inference.huggingface.co:443 ssl:default [getaddrinfo failed]
Time taken: 0.00 seconds

Model: gpt-4o
Provider: Koala
Error: Cannot connect to host koala.sh:443 ssl:default [getaddrinfo failed]
Time taken: 0.00 seconds

Model: gpt-4o
Provider: Liaobots
Error: Cannot connect to host liaobots.work:443 ssl:False [getaddrinfo failed]
Time taken: 0.00 seconds

Model: gpt-4o
Provider: Local
Error: Install "gpt4all" package | pip install -U g4f[local]
Time taken: 0.00 seconds

Model: gpt-4o
Provider: MetaAI
Error: Cannot connect to host www.meta.ai:443 ssl:default [getaddrinfo failed]
Time taken: 0.00 seconds

Model: gpt-4o
Provider: MetaAIAccount
Error: Cannot connect to host www.meta.ai:443 ssl:default [getaddrinfo failed]
Time taken: 0.03 seconds

Model: gpt-4o
Provider: MyShell
Error: <urlopen error [Errno 11001] getaddrinfo failed>
Time taken: 0.03 seconds

Model: gpt-4o
Provider: Ollama
Error: HTTPConnectionPool(host='127.0.0.1', port=11434): Max retries exceeded with url: /api/tags (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000002BE3EB315A0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
Time taken: 2.04 seconds

Model: gpt-4o
Provider: OpenRouter
Error: Add a "api_key"
Time taken: 0.00 seconds

Model: gpt-4o
Provider: Openai
Error: Add a "api_key"
Time taken: 0.00 seconds

Model: gpt-4o
Provider: OpenaiAccount
Error: No .har file found
Time taken: 0.00 seconds

Model: gpt-4o
Provider: OpenaiChat
Error: Cannot connect to host chatgpt.com:443 ssl:default [getaddrinfo failed]
Time taken: 0.00 seconds

Model: gpt-4o
Provider: PerplexityAi
Error: <urlopen error [Errno 11001] getaddrinfo failed>
Time taken: 0.03 seconds

Model: gpt-4o
Provider: PerplexityApi
Error: Add a "api_key"
Time taken: 0.00 seconds

Model: gpt-4o
Provider: PerplexityLabs
Error: Failed to perform, curl: (6) Could not resolve host: www.perplexity.ai. See https://curl.se/libcurl/c/libcurl-errors.html first for more details.
Time taken: 0.00 seconds

Model: gpt-4o
Provider: Pi
Error: <urlopen error [Errno 11001] getaddrinfo failed>
Time taken: 0.03 seconds

Model: gpt-4o
Provider: Pizzagpt
Error: Cannot connect to host www.pizzagpt.it:443 ssl:default [getaddrinfo failed]
Time taken: 0.00 seconds

Model: gpt-4o
Provider: Poe
Error: Model are not supported: gpt-4o
Time taken: 0.00 seconds

Model: gpt-4o
Provider: Raycast
Error: HTTPSConnectionPool(host='backend.raycast.com', port=443): Max retries exceeded with url: /api/v1/ai/chat_completions (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000002BE3EB338B0>: Failed to resolve 'backend.raycast.com' ([Errno 11001] getaddrinfo failed)"))
Time taken: 0.00 seconds

Model: gpt-4o
Provider: Reka
Error: No cookies found for chat.reka.ai
Time taken: 0.03 seconds

Model: gpt-4o
Provider: Replicate
Error: api_key is missing
Time taken: 0.00 seconds

Model: gpt-4o
Provider: ReplicateImage
Error: Failed to perform, curl: (6) Could not resolve host: homepage.replicate.com. See https://curl.se/libcurl/c/libcurl-errors.html first for more details.
Time taken: 0.00 seconds

Model: gpt-4o
Provider: TalkAi
Error: <urlopen error [Errno 11001] getaddrinfo failed>
Time taken: 0.04 seconds

Model: gpt-4o
Provider: Theb
Error: <urlopen error [Errno 11001] getaddrinfo failed>
Time taken: 0.03 seconds

Model: gpt-4o
Provider: ThebApi
Error: Add a "api_key"
Time taken: 0.00 seconds

Model: gpt-4o
Provider: Vercel
Error: HTTPSConnectionPool(host='chat.vercel.ai', port=443): Max retries exceeded with url: /openai.jpeg (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000002BE3EB30220>: Failed to resolve 'chat.vercel.ai' ([Errno 11001] getaddrinfo failed)"))
Time taken: 0.00 seconds

Model: gpt-4o
Provider: WhiteRabbitNeo
Error: Cannot connect to host www.whiterabbitneo.com:443 ssl:default [getaddrinfo failed]
Time taken: 0.03 seconds

Model: gpt-4o
Provider: You
Error: [WinError 1225] The remote computer refused the network connection
Time taken: 13.22 seconds

Model: gpt-4o
Provider: Yqcloud
Error: Failed to perform, curl: (60) SSL certificate problem: certificate has expired. See https://curl.se/libcurl/c/libcurl-errors.html first for more details.
Time taken: 16.51 seconds

